# Neoforge specifics -- largely unchanging
neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28
minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1)
neo_version=21.0.143
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

# Mod Settings
mod_id=vtweaks
mod_name=V-Tweaks
mod_license=GNU GPLv3
mod_version=4.0.14
mod_group_id=com.oitsjustjose.vtweaks
mod_authors=oitsjustjose
mod_description=Minor changes and QOL tweaks to the vanilla experience without adding any new items or blocks!

# Dependency Settings
jei_version=19.5.3.67

# JVM Arg Specifications
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false
